- name: condition using the gather facts
  hosts: web
  become: yes

  tasks:
    - name: install httpd in AMI2023
      dnf:
        name: httpd
        state: present
      when: ansible_facts.distribution_major_version == "2023"
    - name: install httpd in AMI2023
      yum:
        name: httpd
        state: present
      when: ansible_facts.distribution_major_version == "2"
