- name: Install and start the apache
  hosts: web
  become: yes
  
  vars:
    aapche_port: 9090
    src_path: /home/ec2-user/learning/index.html
    dest_path: /var/www/html

  tasks:
    - name: Install the apache/httpd
      dnf:
        name: httpd
        state: present
    - name: Start the apache/httpd
      service:
        name: httpd
        state: started
      tags:
        - start
    - name: Copy the file from controller to target
      copy:
        src: "{{ src_path }}"
        dest: "{{ dest_path }}"
    - name: Ensure the default Apache port is "{{ aapche_port }}"
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen '
        insertafter: '^#Listen '
        line: "Listen {{ aapche_port }}" 
