- name: Install and start the apache
  hosts: web
  become: yes


  tasks:
    - name: Install the apache/httpd
      dnf:
        name: httpd
        state: present
    - name: Start the apache/httpd
      service:
        name: httpd
        state: started
    - name: Copy the file from controller to target
      copy:
        src: /home/ec2-user/learning/index.html
        dest: /var/www/html
    - name: Ensure the default Apache port is 9090
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen '
        insertafter: '^#Listen '
        line: Listen 9090 
      notify: ReStart1 the apache/httpd        
  handlers:      
    - name: ReStart1 the apache/httpd
      service:
        name: httpd
        state: restarted        
