- name: Install and start the apache
  hosts: web 
  become: yes
  
  
  tasks:
    - name: Install the apache/httpd 
      dnf:
        name: httpd
        state: present 
    - name: Start the apache/httpd 
      service:
        name: httpd
        state: started 
