- name: Install the apache, git, docker
  hosts: web 
  become: yes 
  
  
  tasks:
    - name: Install the apache, git, docker using the loop
      dnf:
        name: "{{ item }}"
        state: absent
      loop:
        - httpd
        - git
        - docker
        - zip
