- name: user creation in loop
  hosts: web 
  become: yes 
  
  
  tasks:
    - name: user creation - test1, test2, test3, test4
      user:
        name: "{{ item }}"
      loop:
        - test1
        - test2
        - test3
        - test4
