- name: Install ,start and deploy the apache
  hosts: apache 
  become: yes
  
  
  tasks:
    - name: Install the apache/httpd 
      dnf:
        name: httpd
        state: present 
    - name: Start the apache/httpd 
      service:
        name: httpd
        state: started 
    - name: Copy the file from controller to target 
      copy:
        src: /home/ec2-user/learning/miniproject/index.html
        dest: /var/www/html
